Safer error-handling mechanism
jpochyla/psst pull request #379
Opened 2023-03-17 19:45 UTC by arch-btw

Hi, this is my first time writing Rust, please go easy on me 🙂 Could you make sure I did it correct? I won't be offended if it's not any good. This error was I think similar to the one found in https://github.com/jpochyla/psst/pull/374

The error was as follows and it would cause the app to crash and shutdown:

> thread 'main' panicked at 'called Result::unwrap() on an Err value: "SendError(..)"', psst-gui/src/controller/playback.rs:219:51

2023-03-17 21:51 UTC, Insprill requested changes
Thank you for the PR! Rust is fun :)

Please run `cargo fmt --all` before committing to ensure your code is styled properly, it doesn't look to be indented.

2023-03-17 21:51 UTC, Insprill commented on psst-gui/src/controller/playback.rs
> +            eprintln!("Error sending message: {:?}", e);
Please use `log::error!` instead of `eprintln!`

2023-03-18 13:18 UTC, arch-btw commented
Thank you so much for your help! I really appreciate it. I made the change and also did `cargo fmt --all`
Feel free to let me know if it's still not proper. 
Thanks again!

2023-03-21 05:44 UTC, Insprill commented
It looks like the indentation still isn't correct, not sure why fmt isn't fixing that. Please indent the method to match the others around it.

2023-03-21 18:54 UTC, arch-btw commented
Sorry about that, I think I messed it up but don't know why.
I ran `cargo fmt --all` again and it did change the file again, so I think it should work now. Thank you!

2023-03-22 06:03 UTC, Insprill approved these changes
LGTM. Thank you!

2023-03-22 06:03 UTC, merged