fix: fix error message on login w/o creds
jpochyla/psst pull request #386
Opened 2023-04-13 08:34 UTC by cloudybyte

addressing #382

2023-04-14 08:53 UTC, Insprill requested changes

2023-04-14 08:53 UTC, Insprill commented on psst-core/src/connection/mod.rs
Should this instead be checked [when the user clicks the log in button](https://github.com/jpochyla/psst/blob/master/psst-gui/src/ui/preferences.rs#L318)?

2023-04-14 09:17 UTC, cloudybyte commented on psst-core/src/connection/mod.rs
I don't think so. Checking for error conditions at the lowest level possible is good practice.
Otherwise reusing the fn in another context would result in the bug occurring again.

2023-04-18 09:13 UTC, cloudybyte commented on psst-core/src/connection/mod.rs
What do you think? @Insprill @jpochyla

2023-04-22 19:18 UTC, Insprill commented on psst-core/src/connection/mod.rs
It could only happen if someone manually modifies the config after logging in, and replaces username or auth_data with an empty string which seems... unlikely, but I suppose it can be handled here.

As an extension to that theoretical scenario, if that's the case, it should probably open the login screen instead of having errors all over the UI.

2023-04-22 19:19 UTC, Insprill requested changes

2023-04-22 19:19 UTC, Insprill commented on psst-core/src/connection/mod.rs
> +        if credentials.username.is_empty() && credentials.auth_data.is_empty() {
Shouldn't this be a `||` instead of a `&&`?

2023-05-03 23:55 UTC, merged