Add follow and unfollow playlist support
jpochyla/psst pull request #399
Opened 2023-05-02 09:48 UTC by takanoro

Users can now follow and unfollow playlists. Updated the UI [context menu] to include buttons for following and unfollowing playlists.

2023-05-03 04:23 UTC, Insprill requested changes
Thank you for the PR! In Spotify, there's a distinction between playlists you've created and those you've followed. You can't unfollow a playlist you created, only delete it. With this PR, if you unfollow a playlist you created, it'll still exist, but won't show in your library. If I'm misunderstanding something, please correct me, but I don't think this is intended behavior.

2023-05-03 05:41 UTC, takanoro commented
Yes, you are correct about the behavior related to unfollowing a playlist you've created. So far, I haven't seen an option to delete such a playlist.

On [spotify web api concepts](https://developer.spotify.com/documentation/web-api/concepts/playlists) page spotify says:

> We have no endpoint for deleting a playlist in the Web API; the notion of deleting a playlist is not relevant within the Spotify’s playlist system. Even if you are the playlist’s owner and you choose to manually remove it from your own list of playlists, you are simply unfollowing it. Although this behavior may sound strange, it means that other users who are already following the playlist can keep enjoying it. [Manually restoring a deleted playlist](https://www.spotify.com/se/account/recover-playlists/) through the Spotify Accounts Service is the same thing as following one of your own playlists that you have previously unfollowed.

As a workaround we can omit "Unfollow" menu item for playlists you've created while retaining the ability to follow and unfollow other playlists.

2023-05-03 06:35 UTC, Insprill commented
Looking at it again, I think the current behavior is fine, and I was just misunderstanding Spotify's UI. As it says in the documentation you referenced, there's no such thing as deleting a playlist. When the Spotify UI says 'Delete', it simply unfollows it, and it can still be accessed and refollowed again if you know its ID.

The only other critique I have is the fact that there's no confirmation before deleting a playlist. I can easily see someone deleting a playlist they meant to copy the link to, and having no way of finding it again. This could be implemented by creating a small child window, similar to how the preferences window is handled, that just has some text and Yes/ No buttons. Implementing that will be a little complex, so if anyone has another idea feel free to share.

2023-05-03 13:44 UTC, takanoro commented
I've added a confirmation dialog window, but since I'm not very familiar with Druid, I may have made some kludges  :police_car: concerning the handling of events in inappropriate places (new window creation and their environment). Additionally, I'm uncertain about the padding and window size of the confirmation dialog window. 

Please, feel free to provide any corrections or suggestions, as I appreciate your input.

2023-05-03 22:26 UTC, Insprill requested changes

2023-05-03 22:26 UTC, Insprill commented on psst-gui/src/ui/playlist.rs
> +        .title("Rename playlist")
I don't think this is correct

2023-05-03 22:26 UTC, Insprill commented on psst-gui/src/ui/playlist.rs
> +        .window_size((theme::grid(45.), theme::grid(20.)))
The height is a little too small to see the buttons. 25 seems to be good.

2023-05-03 22:26 UTC, Insprill commented on psst-gui/src/ui/playlist.rs
> +        .with_child(delete_button)
The delete button should go first, seems more intuitive.

2023-05-03 22:26 UTC, Insprill commented on psst-gui/src/ui/playlist.rs
> +            };
This can be moved up with `created_by_user` being set to `library.is_created_by_user(playlist)`

2023-05-04 03:13 UTC, takanoro commented
Thank you for the review! 
It seems that I have incorporated all the suggestions into the code and corrected the typos.

2023-05-04 03:43 UTC, Insprill approved these changes
LGTM. Thank you!

2023-05-04 03:58 UTC, merged