Increase timeout when using proxy
jpochyla/psst pull request #436
Opened 2023-09-08 01:53 UTC by arch-btw

On large playlists and/or high-latency networks there is not enough time for all album covers to finish downloading. 

> WARN  psst_gui::delegate] failed to fetch image: https://i.scdn.co/image/... Connection Failed: tls connection init failed: Resource temporarily unavailable (os error 11)

Thank you :smiley:

2023-09-09 23:42 UTC, jacksongoode commented
Thanks for the PR! @Insprill do you think this would cause any side effects? I think it's within reason for long playlists.

2023-09-10 17:35 UTC, Insprill requested changes

2023-09-10 17:35 UTC, Insprill commented on psst-core/src/util.rs
> +pub const NET_CONNECT_TIMEOUT: Duration = Duration::from_millis(16 * 1000);
Does the connection timeout need to be increased?

2023-09-10 19:57 UTC, arch-btw commented
Hello, thank you both! 
Yes you're right, only NET_IO_TIMEOUT needs an increase for this to work, not the other one.

2023-10-04 22:09 UTC, jacksongoode commented
@Insprill I can remove the change from NET_CONNECT_TIMEOUT and we can merge?

2023-10-04 22:20 UTC, Insprill commented
Yeah that'd be good, I'd like to get this merged too.

2023-10-05 01:17 UTC, jacksongoode commented
See https://github.com/jpochyla/psst/pull/442

2023-10-05 01:17 UTC, closed without merging